import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} h-screen flex flex-col`}
      >
        <header className="items-center justify-between w-full bg-gray-200 p-4">
          <h1 className="text-2xl font-bold">Header</h1>
        </header>
        <main className="flex-1 overflow-auto">{children}</main>
        <footer className="bg-neutral-700 text-white py-4">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex justify-center">
            <h1>FOOTER</h1>{" "}
          </div>
        </footer>
      </body>
    </html>
  );
}
